name: .NET Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .net framework env
      uses: vrnobody/Setup-DotNetFrameworkEnv@v1
    - name: Restore Nuget packages
      run: nuget restore RazerChromaMqtt.sln
    - name: Build solution
      run: msbuild RazerChromaMqtt.sln -p:Configuration=Release 
    - name: Build Setup
      run: msbuild RazerChromaMqtt/RazerChromaMqttSetup.vdproj -p:Configuration=Release 
    - name: upload Output .msi
      uses: actions/upload-artifact@v1
      with:
        name: RazerChromaMqttSetup.msi
        path: ${{ github.workspace }}/RazerChromaMqttSetup/Release/RazerChromaMqttSetup.msi
    - name: upload Output .exe
      uses: actions/upload-artifact@v1
      with:
        name: setup.exe
        path: ${{ github.workspace }}/RazerChromaMqttSetup/Release/setup.exe
